# Based on https://github.com/shalzz/zola-deploy-action/blob/964938f983e3223fbe16fcc626ff1ad803dba1cd/README.md?plain=1#L19
# Ensure that GITHUB_TOKEN has Read and Write permissions in Repository Settings/Actions/General/Workflow permissions.
name: Zola on GitHub Pages

on:
 push:
  branches:
   - main

jobs:
  build:
    name: Publish site
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@v4
    - name: Build and deploy
      uses: shalzz/zola-deploy-action@v0.18.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
